# Generated by Django 6.0 on 2026-01-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('inicio', models.CharField(max_length=20)),
                ('fin', models.CharField(default='Actualidad', max_length=20)),
                ('logros', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermedio'), ('A', 'Avanzado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
            ],
        ),
    ]
