# Generated by Django 6.0 on 2026-01-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='imagen',
        ),
        migrations.AddField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(default='temp', upload_to='certificados/'),
            preserve_default=False,
        ),
    ]
