# Generated by Django 6.0 on 2026-01-03 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_perfil_apellido_perfil_ciudad_perfil_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='fecha_nacimiento',
            new_name='fechanacimiento',
        ),
        migrations.AddField(
            model_name='certificado',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='cv.perfil'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.perfil'),
        ),
        migrations.AddField(
            model_name='habilidad',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='cv.perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direcciondomiciliaria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estadocivil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='lugarnacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numerocedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
