# Generated by Django 6.0 on 2026-01-03 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_rename_fecha_nacimiento_perfil_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='direcciontrabajo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='github',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefonofijo',
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Referencia')),
                ('telefono', models.CharField(max_length=20, verbose_name='Número de Celular')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='cv.perfil')),
            ],
        ),
    ]
