# Generated by Django 6.0 on 2026-01-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_remove_perfil_direcciontrabajo_remove_perfil_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
