# Generated by Django 6.0 on 2026-01-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_referencia_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
