# Generated by Django 6.0 on 2026-01-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tiposangre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
