# Generated by Django 6.0 on 2026-01-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_perfil_direcciontrabajo_perfil_tiposangre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidad',
            name='nivel',
        ),
        migrations.AddField(
            model_name='habilidad',
            name='categoria',
            field=models.CharField(choices=[('T', 'Técnica'), ('B', 'Blanda')], default='T', max_length=1),
        ),
    ]
